name: build and publish
on:
  workflow_dispatch:
  release:
    types: [ created ]
  push:
    branches: [ $default-branch ]

jobs:
  publish:
    uses: Opetushallitus/.github/.github/workflows/build-java-package.yml@main
