name: build and publish
on:
  workflow_dispatch:
  release:
    types: [ created ]
  push:
    branches: [ $default-branch ]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '#INSERT_JAVA_VERSION_HERE_8_11_17#'
          distribution: 'corretto'
          cache: 'maven'

      - name: Run tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean package

      - name: Publish to Github
        if: github.ref == 'refs/heads/$default-branch'
        continue-on-error: true
        run: mvn deploy --batch-mode --projects . -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/Opetushallitus/$REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}

      - name: Publish to Artifactory
        if: github.ref == 'refs/heads/$default-branch'
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          mvn deploy --batch-mode --projects . --settings ci-tools/common/maven-settings.xml -DaltDeploymentRepository=oph-sade-artifactory::default::https://artifactory.opintopolku.fi/artifactory/oph-sade-release-local -DaltSnapshotDeploymentRepository=oph-sade-artifactory::default::https://artifactory.opintopolku.fi/artifactory/oph-sade-snapshot-local
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}