name: Push java package

on:
  workflow_call:
    inputs:
      application:
        description: 'Name of the application being built (service name in AWS)'
        required: true
        type: string
      base-image:
        description: 'Image used as the base (example: utility/fatjar-openjdk11:master)'
        required: true
        type: string
      configfolder:
        description: 'Location of config which is copied to image'
        required: true
        type: string
      jarfile:
        description: 'Jarfile with dependencies, use * for changing elements (example: kouta-internal-*-with-dependencies.jar)'
        required: true
        type: string
      jarfolder:
        description: 'Folder which contains the jarfile mentioned above'
        required: false
        default: 'target'
        type: string
      working-directory:
        description: 'Define starting directory for monorepos'
        required: false
        type: string
        default: '.'
      download-artifact:
        description: 'Downloads the artifact instead of fetching it from cache, set download-artifact-name if you set this to true'
        required: false
        type: boolean
        default: false
      download-artifact-name:
        description: 'Name of the artifact downloaded with download-artifact'
        required: false
        type: string
        
    secrets:
      AWS_UTILITY_ROLE_ARN:
        required: true

env:
  DOCKER_BUILD_DIR: '/tmp/docker_build'
  ARTIFACT_DEST_PATH: '/usr/local/bin'

jobs:
  push:
    name: Push and scan java image
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit
      
      - uses: actions/checkout@v4
          
      - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
        if: ${{ inputs.download-artifact == false }}
        id: restore-build
        with:
          path: |
            ${{ inputs.jarfolder }}
          key: ${{ github.sha }}
      
      - uses: actions/download-artifact@v4
        if: ${{ inputs.download-artifact == true }}
        with:
          name: ${{ inputs.download-artifact-name }}

      - name: Check that there is a .jar file available in jarfolder
        run: |
          count=$(find ${{ inputs.jarfolder }}/${{ inputs.jarfile }} -type f | wc -l)
          if [ $count -eq 0 ]
          then
            exit 1
          else
            exit 0
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3
        id: buildx

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ secrets.AWS_UTILITY_ROLE_ARN }}
          role-session-name: ${{ inputs.application }}-push-image
          aws-region: eu-west-1

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2

      - name: Login to docker with ECR
        uses: docker/login-action@aad0f974f21dc644b324e9fa84c4e364f62acbe6 # v3
        with:
          registry: ${{ steps.ecr-login.outputs.registry }}

      - name: Prepare for build
        shell: bash
        env:
          ECR_REPO: ${{ steps.ecr-login.outputs.registry }}
        run: |
          mkdir -p $DOCKER_BUILD_DIR && mkdir $DOCKER_BUILD_DIR/config && mkdir $DOCKER_BUILD_DIR/artifact
          curl -LJO --output-dir $DOCKER_BUILD_DIR https://raw.githubusercontent.com/Opetushallitus/ci-tools/master/github-build/Dockerfile
          cp -v ${{ inputs.jarfolder }}/${{ inputs.jarfile }} $DOCKER_BUILD_DIR/artifact/${{ inputs.application }}.jar
          cp -vr ${{ inputs.configfolder }} $DOCKER_BUILD_DIR/config/
          sed -i -e "s|BASEIMAGE|${ECR_REPO}/utility/${{ inputs.base-image }}|g" ${DOCKER_BUILD_DIR}/Dockerfile
          if [ -d "${DOCKER_BUILD_DIR}/native_libs" ]; then sed -i '/^CMD.*/i COPY native_libs/* /usr/lib' ${DOCKER_BUILD_DIR}/Dockerfile; fi

      - name: Docker meta for image
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: |
            ${{ steps.ecr-login.outputs.registry }}/utility/${{ inputs.application }}
          tags: |
            type=raw,value=ga-${{ github.run_number }}
            type=raw,value=${{ github.ref_name }}

      - name: Build image
        id: build-push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        with:
          context: ${{ env.DOCKER_BUILD_DIR }}
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            name=${{ inputs.application }}
            artifact_destination=${{ env.ARTIFACT_DEST_PATH }}

      - name: Update build metadata
        shell: bash
        run: |
          BUILD_TIMESTAMP=`TZ='Europe/Helsinki' date +'%Y-%m-%d %H:%M:%S %Z'`
          aws dynamodb put-item --table-name builds --item "{\"Service\": {\"S\": \"${{ inputs.application }}\"}, \"Build\": {\"S\": \"ga-$GITHUB_RUN_NUMBER\"}, \"Branch\": {\"S\": \"$GITHUB_REF_NAME\"}, \"Commit\": {\"S\": \"$GITHUB_SHA\"}, \"Time\": {\"S\": \"$BUILD_TIMESTAMP\"}}" --condition-expression "attribute_not_exists(Id)" --region eu-west-1

      - name: Scan image
        id: scan
        uses: aquasecurity/trivy-action@1f6384b6ceecbbc6673526f865b818a2a06b07c9 # master
        with:
          image-ref:  ${{ steps.ecr-login.outputs.registry }}/utility/${{ inputs.application }}:ga-${{ github.run_number }}
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'